# Generated by Django 2.1 on 2020-10-20 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('audio_file', models.FileField(upload_to='')),
                ('title', models.CharField(max_length=100)),
                ('uploaded_date', models.DateTimeField()),
                ('people', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(null=True)),
                ('start_t', models.CharField(max_length=200, null=True)),
                ('end_t', models.CharField(max_length=200, null=True)),
                ('record_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetingapp.Record')),
            ],
        ),
    ]
