# Generated by Django 2.1 on 2020-10-20 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='speaker_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='speaker_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
