# Generated by Django 2.1.7 on 2020-10-23 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingapp', '0002_auto_20201020_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='user_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='record_id',
            field=models.CharField(max_length=200),
        ),
    ]
