# Generated by Django 2.1 on 2020-11-05 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetingapp', '0003_auto_20201023_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='record',
            name='uploaded_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='text',
            name='record_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetingapp.Record'),
        ),
    ]
